<?php

/**
 * Created by PhpStorm.
 * User: fiefioor
 * Date: 05.03.16
 * Time: 14:36
 */
class CInputShape extends InputShape
{


    public function preFill()
    {
        // TODO: Implement preFill() method.
    }

    public function postFill()
    {
        // TODO: Implement postFill() method.
    }

    public function fill()
    {
        parent::fill(); // TODO: Change the autogenerated stub

        //return "scanf(\"%d\", &".$this->getContent().");";
        return "std::cin >> n;";

    }
}